### PR TITLE
Append SVG class functionality

### PR DESCRIPTION
**Pull request by maartenbrakkee**
Added ESlint, `.editorconfig` and append class functionality.

### CODE REVIEW

**Comment by brob** [comment]
I missed this when you issued the PR, sorry about that! 

This is an amazing update for the codebase, so thank you so much! The new feature is great and the refactor to a Class is a welcome update!

Two questions:

1. You replaced JSDom with Cheerio. I actually know more about Cheerio than JSDom, but I'm wondering what made you want to change. Was it just simplifying the syntax or reducing code or was there something in JSDom that wasn't quite working?

2. I don't mind attaching some ESLint rules to the repository to make contributions easier, but would you mind updating the indent space count to 4 instead of 2?

**Comment by maartenbrakkee** [comment]
Hi brob, thanks for your message.

1. I experienced some speed improvements while using Cheerio.

2. The [airbnb-base](https://github.com/airbnb/javascript) is set for ESlint. They [set soft tabs to 2 spaces](https://github.com/airbnb/javascript#whitespace--spaces). In my opinion, it should be good to follow the standard, but feel free to change it.

**Comment by brob** [comment]
In reviewing, I'm also seeing that this new functionality only works in Nunjucks. I'm trying to keep this working for both Liquid and Nunjucks as a "universal filter."

The issue is with the destructuring as Liquid only allows for strings to be passed to filters.

I'd be curious to get your opinion on the best way to handle it. In this simple plugin, it might be, we just don't pass in the `class="classname"` and instead just pass in `"classname"`.

If we want to keep the syntax for future features, we need to probably split it into two addFilters to have a Nunjucks version and a universal.

I did that in this in my "blog tools" plugin. I don't really like it overall because it's not DRY, but I haven't come up with a better solution. If you have any ideas on a better solution, I'd love to hear it: https://github.com/brob/eleventy-plugin-blog-tools/blob/master/.eleventy.js#L14

**Comment by brob** [comment]
Tweaked this to work in Liquid and nunjucks and merged it in! Thanks so much for all the cleanup work you did and the new feature!

**Pull request merged**
